spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

management.endpoints.web.exposure.include=health,info,metrics,mappings
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=demo
info.app.description=API de usuarios con Spring Boot
info.app.version=1.0.0

logging.level.root=INFO
logging.level.com.example.demo=DEBUG
