spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db
spring.datasource.username=demo_user
spring.datasource.password=demo_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=false

management.endpoints.web.exposure.include=health,info,metrics,mappings
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=demo
info.app.description=API de usuarios con Spring Boot
info.app.version=1.0.0